### PR TITLE
Enable Resource Scoping

### PR DESCRIPTION
**Pull request by Chaseshak**
This pull request allows us to save and retrieve objects (Documents, Announcements, etc.)  with a scope using a user's roles.

To accomplish this, I wanted to be able to call methods that had to do with setting the scope of a resource and retrieving scoped resources to appear like class methods and class instance methods. This is achieved through the implementation of a module.

When you `include` a module, you can call its methods like instance methods. When you `extend` a module you can call its methods like class methods. This allows us to replace `Document.all` with `Document.scoped(current_user)` to get the scope of documents a current user can see.

Then when saving a scoped resource, we can simply call `@document.scopify(roles)` and that document instance will have a specific scope.

### CODE REVIEW

**Comment by georgemblack** [comment]
This looks so cool! I'll give it a run and review it once the conflicts are resolved.

**Comment by Chaseshak** [comment]
Woops there weren't any merge conflicts when I asked for a review.. more stuff got pushed to master. Should be good now @georgemblack

**Comment by Chaseshak** [comment]
It's the merge from master that broke it. Now that there's a scoped function returning announcements, it returns an array, not an Active record Object. So if you call .limit(5) on it in the home view, you get an error. I think I'm going to add an optional param to the function that allows you to pass in a limit on how many you want. And an offset for pagination of results.

**Comment by georgemblack** [comment]
My bad – I made a change on another branch to fix a bug, then it got merged with master without taking into account changes on this branch.

Would you like to me to quick change it back to `@announcements[0..4]`? That should fix the issues showing up here.

**Comment by georgemblack** [comment]
Looks good!

**Pull request merged**
