### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by rbrezynski**
Will continuously be pulling from master in this branch in order to write extra tests as needed

### CODE REVIEW

**Comment by Chaseshak** [comment]
Most of the tests should be complete now.

The remaining tests are largely in `*_helper.rb` files.

One thing we should consider is maybe the logic (in at least the `announcement_helper.rb` file) should perhaps exist elsewhere. Since @georgemblack pointed out in Slack, helpers should be helpers for the view, not the controller. We may want to abstract this logic into a model or another place. Thoughts @rbrezynski ?

**Comment by rbrezynski** [comment]
@Chaseshak yep, originally I was triggering the send on click inside of the view, but I will move it

**Comment by rbrezynski** [comment]
Moved the code. Ready to be approved https://github.com/Chaseshak/BadgerNet/pull/51

**Comment by Chaseshak** [comment]
@rbrezynski Looks good! Let's merge this one first since it was merged into your newer branch. I will try and write the rest of the tests for the other 2 files if I can.

**Comment by Chaseshak** [comment]
Woops... I copied the format of the announcement helper spec and forgot to change the name. Not sure why that test is failing for you? It passes on Travis and I can't cause it to fail locally.

**Pull request merged**
